name: Java CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'adopt'
      - name: Build with Maven
        run: mvn clean package

      - name: Build the Docker image
        run: docker build -t cicdtest .
      - name: Run within Docker
        # You may pin to the exact commit or the version.
        # uses: mosteo-actions/docker-run@1e8c2ac951679fbb21485cbb4eed9e39246ad823
        uses: mosteo-actions/docker-run@v1
        with:
          # A dockerhub image
          image: cicdtest
